### ISSUE TITLE
fails to create output directory

### ISSUE THREAD

**Issue by garymazz** [wix-maven/wix-maven-plugin#8]
During light execution, the output directory structure is not created.

Error reported: `....target\wixobj\Release\x64 does not exist`
The output directory should be either:
1. documented
2. made configurable
3. created on demand.

**Comment by GregDomjan** [comment]
It would be helpful to have the stack trace.
This location is better identified as the intermediate directory or `<intDirectory/>`
It has the architecture appended to it.
1. It's documented
   - http://wix-maven.github.io/wix-maven-plugin/candle-mojo.html
   - http://wix-maven.github.io/wix-maven-plugin/light-mojo.html
2. It's configurable
3. It would be created if something was compiled using candle. It should be ignored if missing during lit or light - at least I thought so based on using `org.codehaus.plexus.compiler.util.scan.SourceInclusionScanner`.  With a stack trace I might be able to look further into this.

**Comment by wburwash** [comment]
[ERROR] Failed to execute goal com.github.wix-maven:wix-maven-plugin:0.1.0:light (default-light) on project msi: Execution default-light of goal com.github.wix-maven:wix-maven-plugin:0.1.0:light failed: basedir C:\Users\[REDACTED]\Documents\workspace\[REDACTED]\target\wixobj\Release\x64 does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.wix-maven:wix-maven-plugin:0.1.0:light (default-light) on project msi: Execution default-light of goal com.github.wix-maven:wix-maven-plugin:0.1.0:light failed: basedir C:\Users\[REDACTED]\Documents\workspace\[REDACTED]\target\wixobj\Release\x64 does not exist
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-light of goal com.github.wix-maven:wix-maven-plugin:0.1.0:light failed: basedir C:\Users\[REDACTED]\Documents\workspace\[REDACTED]\target\wixobj\Release\x64 does not exist
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.IllegalStateException: basedir C:\Users\[REDACTED]\Documents\workspace\[REDACTED]\target\wixobj\Release\x64 does not exist
        at org.codehaus.plexus.util.DirectoryScanner.scan(DirectoryScanner.java:308)
        at org.codehaus.plexus.compiler.util.scan.AbstractSourceInclusionScanner.scanForSources(AbstractSourceInclusionScanner.java:78)
        at org.codehaus.plexus.compiler.util.scan.SimpleSourceInclusionScanner.getIncludedSources(SimpleSourceInclusionScanner.java:62)
        at com.github.wix_maven.LightMojo.multilink(LightMojo.java:128)
        at com.github.wix_maven.AbstractLinker.execute(AbstractLinker.java:248)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by GregDomjan** [comment]
In effect it is saying it has not compiled any source .wxs into intermediate .wixobj or .wixlib in the previous candle goal for x64.
As such when it tries to link drawing in the intermediate it can't find any.

I'll make this more robust and check for the folder before calling the scanner to avoid this exception.

Have a doubt it will not resolve your build.
I'm not aware of any build path that allows for linking with Light or Lit that works without at least 1 .wxs file and candle compile.
